### ISSUE TITLE
Resolve Known Issue: LaterPay API Fallback behavior

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1009]
There is an existing feature on the Settings page which should allow a merchant to select how they would like the plugin to behave if the LaterPay API is not responding. Their current options are:
- Do nothing (No user can access premium content while the LaterPay API is not responding.)
- Give full access
- Hide premium content
Current behavior: Give full access regardless of what the merchant has selected

The current WordPress behavior matches with the current Connector behavior and with the Connector, merchants are not given an option to change this behavior.

Unless we get significant pushback from our existing merchants, we should simply remove this section as well as any associated code.

**Comment by thrijith** [comment]
@ksmoore125

>Current behavior: Give full access regardless of what the merchant has selected

I am not sure if this is working right now. I've tested with all three options. When `Do nothing` or `Give full access`  is selected paywall is shown on the content. And when `Hide premium content` is selected I can see it shows `post not found`.

I've not checked the code in detail. LMK what has to be done here. If we are moving forward with code removal for this it might take around 1-2 hour(s) or so as access is something that is checked every time. So that needs to be handled carefully and tested.

**Comment by ksmoore125** [comment]
Just to clarify, it sounds like below is the status of the three options:
`Do nothing` - **Working** - paywall is shown
`Hide premium content` - **Working** - post is not found
`Give full access` - **NOT Working** - paywall is shown when instead this option should make all content free

If this is the case, we should leave this option on the Settings page and fix the `Give full access` option

**Comment by ksmoore125** [comment]
@thrijith, Can you please let me know how I can test the site's behavior as is if the API has failed?

**Comment by thrijith** [comment]
Fixed and released in [2.3.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.3.0)
