### ISSUE TITLE
Move “LaterPay Enabled Post Types” from LaterPay Settings page to the Pricing tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1016]
### User Story
As a LaterPay Merchant, I do not want to have to hunt for hidden functionality. Especially not items essential to the initial plugin configuration.

### Acceptance Criteria

- Move “LaterPay Enabled Post Types” from LaterPay Settings page to the top of the Pricing tab
- No change in functionality

### Mock-up
![image](https://user-images.githubusercontent.com/41650164/47112343-b22c5580-d21b-11e8-84a8-0fa9b14e157b.png)

**Comment by thrijith** [comment]
@ksmoore125 This should not take more than a day or less once the new structure is in place.

**Comment by thrijith** [comment]
@ksmoore125 I've done changes for this, but it's a bit different from the given mockup.

![screenshot 2018-11-19 at 4 23 17 pm](https://user-images.githubusercontent.com/13589980/48702662-7bc96800-ec17-11e8-8f7c-00c0ee884713.png)

Changes and Queries:

1) There are no buttons in the mockup for updating the enabled post type. 

If you were expecting to update the setting on change of checkbox selection. Let me know.
It won't be good to update the option on change of checkbox selection, because it will hit DB very frequently.

2) The text under `Default Pricing` might confuse users as there isn't a `Custom Pricing` tab yet.
Let me know if the current text of the `Pricing` tab needs to be changed and whether the description needs to be updated.

**Comment by ksmoore125** [comment]
1. The Save / Cancel buttons are acceptable
2. Good catch! Please replace the text with:
> ### Paid Content
> Please choose which of the following post types are eligible to be sold with LaterPay.

**Comment by thrijith** [comment]
Fixed and released in [2.3.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.3.0)
