### ISSUE TITLE
Google Analytics Enhancements

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1101]
We are currently sending all Google Analytics tracking data to our US Sandbox account. Instead, we should update this so that the data is sent to the appropriate GA account:

If Region = United States
- Sandbox: UA-50448165-10 (current)
- Live: UA-50448165-9

If Region = Europe
- Sandbox: UA-50448165-4
- Live: UA-50448165-3

Use Sandbox Google Analytics accounts when LaterPay plugin is in TEST mode
Use Live Google Analytics accounts when LaterPay plugin is in LIVE mode

**Comment by thrijith** [comment]
@ksmoore125 UA codes are used according to region and plugin-mode only.

The other pages/tab that have old UA code need to be refreshed in order to get the new one. ( During implementation of the feature we faced the same kind of issue with merchant id on plugin mode change. )

Please let me know if you have any concerns.

Thanks

**Comment by ksmoore125** [comment]
This works properly.
