### ISSUE TITLE
Add "I already bought this" link to Time Passes & Subscription Area

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1131]
### User Story
Our merchant Der Bank Blog would like to use the 'Teaser + Purchase Link' Appearance option but using Custom Positioning and hiding the Purchase Button. When they do this, the "I already bought this" link is no longer available.

### Acceptance Criteria
As a simple solution, we should add the "I already bought this link" to the bottom of the article as well. 

### Mockup
![image](https://user-images.githubusercontent.com/41650164/53268174-f7213680-36aa-11e9-8f6a-2ed8cfad73d6.png)

**Comment by thrijith** [comment]
Since the link is not visible when Custom Position is enabled and an alternative purchase button is not provided.

As rest of the layouts already have this link, I have added it to the end of the content, only for `Teaser + Purchase Link` layout when `Custom Position` is selected.

When Time Pass / Subscription is available.

![screenshot 2019-02-25 at 9 03 30 pm](https://user-images.githubusercontent.com/13589980/53348347-e5f15780-3940-11e9-943b-8daafdcba74c.png)

When Time Pass / Subscription is  not available.

![screenshot 2019-02-25 at 9 03 46 pm](https://user-images.githubusercontent.com/13589980/53348364-ee499280-3940-11e9-8326-7ac4c5b9d6f1.png)

@ksmoore125 Please check and let me know if ok.

**Comment by ksmoore125** [comment]
This looks great, thanks!

**Comment by thrijith** [comment]
Released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
