### ISSUE TITLE
Ajax request in caching compatible mode skips enqueueing of other plugins

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#119]
The post content we fetch in page caching compatible mode is incomplete.
Other plugins do not seem to have the opportunity to process shortcodes and include their scripts accordingly.
For example the slideshow feature of the Jetpack plugin relies on a shortcode and enqueues its scripts, if such a shortcode is found in the post content. But that doesn't happen, if a post has a price > 0 and the plugin is in page caching compatible mode.
There should be a way to ensure that all post-processing of the content has taken place in the version of the post content that we fetch.

**Comment by larsschenk** [comment]
In caching compatible mode I have the shortcode from "Contact Form 7" not processed while the [caption] shortcode is processed correct.

I see:
````
[contact-form-7 id=”843488″ title=”something”]
````
in the page or post instead of the form. So I wonder if shortcodes from plugins are broken or if something is wrong with the Contact Form 7 plugin/shortcodes. (The form is showing up correct on a free page/post.) I have not yet tested other shortcodes from other plugins.

Thx for pointing me into the right direction on how to investigate further.
