### ISSUE TITLE
`/validatesignature` event is being called twice every time a paywall is viewed

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1382]
# Description
At LaterPay we discovered that our log files were being bogged down with API calls which all corresponded to WordPress merchants. Upon further debugging, it appears that each time a paywall is viewed, the `/validatesignature` API is being called at least twice. Based on my current understanding of how the API works, this API should not be called except for when the "mode" toggle on the Account tab is changed to `LIVE`

**Comment by thrijith** [comment]
>  Based on my current understanding of how the API works, this API should not be called except for when the "mode" toggle on the Account tab is changed to LIVE

@ksmoore125 above statement is true, apart from that there is a check involved before adding a paywall, i.e to hide the paywall in case an account in disabled, added as a fix for https://github.com/laterpay/laterpay-wordpress-plugin/issues/1251

The first check is the one mentioned above to verify account validity, other check is added after that which checks availability of the API for fallback behaviour of post content.

The fix for repeated call is deployed on staging, please verify https://github.com/laterpay/laterpay-wordpress-plugin/issues/1251 is working as expected by disabling the account.

Also here is a related article related to API call https://github.com/laterpay/laterpay-wordpress-plugin/issues/915

**Comment by thrijith** [comment]
Fixed in [v2.9.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.3)
