### ISSUE TITLE
/validatesignature Phase 2

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1392]
# Details
Per conversations with the LaterPay team ([here](https://laterpay.slack.com/archives/DC17TUM89/p1582560926022800) & [here](https://laterpay.slack.com/archives/CGA4Y3H08/p1584126209007000)) we should further limit the `/validatesignature` call.

This relates to #1392 

# Acceptance Criteria
- Ensure that `/validatesignature` is eliminated completely when a user visits the home page of the site if the user selects `disable content access check queries on Home Page`
![image](https://user-images.githubusercontent.com/41650164/78564788-95565a00-77e2-11ea-8c6d-c58c1e1e2766.png)

- If the following is indeed possible, we should implement this change as well:
> https://github.com/laterpay/laterpay-wordpress-plugin/blob/b98e7ca4ab49b4928d230e5799c5c95835442b19/laterpay/application/Helper/Request.php#L157-L170
> 
> if I understand correctly we can just drop those lines and with it the additional health check on page load

**Comment by thrijith** [comment]
> Ensure that /validatesignature is eliminated completely when a user visits the home page of the site if the user selects disable content access check queries on Home Page

This is fixed.


> If the following is indeed possible, we should implement this change as well
> if I understand correctly we can just drop those lines and with it the additional health check on page load

@ksmoore125 The existing check was done to handle fallback back behaviour if the LaterPay API is not responding.

If user had access to articles it would respond with and array of articles, when user didn't have one it checked the health endpoint to verify availability.

We added an additional check on each page load to switch account mode to test if merchant account was disabled, it was moved here which caused duplicate requests that was fixed in previous release v2.9.3.

If the account validation check added for https://github.com/laterpay/laterpay-wordpress-plugin/issues/1251 isn't necessary we can remove it, Pleas let me know if it should be removed.

**Comment by ksmoore125** [comment]
We can remove the access check that was added for #1251 

Additionally, I will reach out to our team to see if they have an alternate suggestion for the fallback behavior.

**Comment by thrijith** [comment]
> Additionally, I will reach out to our team to see if they have an alternate suggestion for the fallback behaviour.

Ok, as of now merchant selects the default fallback behaviour from settings page.

![lp-fb](https://user-images.githubusercontent.com/13589980/78693434-dc466b80-7918-11ea-8c5d-36a85531a3e4.png)

**Comment by thrijith** [comment]
> We can remove the access check that was added for #1251

@ksmoore125 Sorry, in case it was not clear, it was an additional check earlier, currently the result of a single request is used to handle #1251 and fallback behaviour.

**Comment by ksmoore125** [comment]
In regards to the fallback behavior, one piece of feedback from our team was:
> I don't really understand why it would need that extra request on every access check. If the response is an empty array (or response is empty), why check another endpoint that is not necessarily designed for a health check? 
> 
> I don't see the benefit of calling `/validatesignature` if the `/access` call doesn't return anything

**Comment by thrijith** [comment]
> I don't really understand why it would need that extra request on every access check. If the response is an empty array (or response is empty), why check another endpoint that is not necessarily designed for a health check?

Both requests are necessary, I'll move the validation check `/validatesignature`, before `/access` request is done, to avoid extra request in case the merchant account is disabled.

> I don't see the benefit of calling /validatesignature if the /access call doesn't return anything

`/access` check returns an empty array when there is no `lptoken` to identify user, in this scenario it would not be possible verify availability of the API, which is when the health check response is used, since the health check is now moved above access check, which validates account we can now avoid request to `access` when account is not valid.

**Comment by thrijith** [comment]
Hi @ksmoore125,

Please check above comment and let me know if you any concerns about the same.

**Comment by thrijith** [comment]
Fixed in [v2.9.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.4)
