### ISSUE TITLE
Plugin breaks when SSL support is enabled

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#544]
Using
```define('FORCE_SSL_ADMIN', true);```
in the wp-config.php apparently causes various errors.
The following problems [have been reported](https://wordpress.org/support/topic/laterpay-button-and-text-disappears-replaced-by-letter-zero):
> If I set a post to paid, the Laterpay button isnt shown on the front page (using excerpts) at all. If I try to access the contents, the teaser and the laterpay button are shown for approximately half a second, then the whole content of the post disappears and is replaced by the letter zero "0".

**Comment by Chrico** [comment]
@drdla 
Do we have a testing-envoirment with SSL enabled? 

Some possible errors:

* It could be possible, that we have an JS-Error, because a script/iframe is loaded without _https_. 
* Sometimes it could also be a problem, when setting the `FORCE_SSL_ADMIN`. that the `$_SERVER['HTTPS']` is empty. Our plugin checks this flag to see, if the urls should be delivered with https. See [here](https://github.com/laterpay/laterpay-wordpress-plugin/blob/65c62dbe8b909ffce1f0c3de25a0d99772dad659/laterpay/application/Helper/Request.php#L20) and [here](https://github.com/laterpay/laterpay-wordpress-plugin/blob/a1c4d2761acd3cc118fe2c641096cc9f621d621f/laterpay/application/Helper/Statistics.php#L172)

**Comment by drdla** [comment]
Just setting one up

**Comment by drdla** [comment]
Everything seems to be working fine with SSL enabled!?

**Comment by Chrico** [comment]
Yep for me too. Just getting following error:

```
easyXDM.min.js:24 Uncaught TypeError: undefined is not a function
```

Maybe we could get some WP- and FTP-Login to the site where the error occurs?

**Comment by drdla** [comment]
Replied to affected user asking for access to his installation, see https://wordpress.org/support/topic/laterpay-button-and-text-disappears-replaced-by-letter-zero?replies=6#post-6471647

**Comment by drdla** [comment]
Could not reproduce issue - everything is working fine with SSL.
Closing this as invalid.
