### ISSUE TITLE
Add option to allow only time pass purchases

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#581]
Currently, there is only the option to sell **individual posts AND time passes**.
There should also be the option to **sell only time passes**, so no individual purchases should be possible.

For this purpose, the following adjustments are necessary:

**Pricing Tab**
- [x] 1) Add a **toggle**, that let's the merchant choose between "**Allow individual and time pass purchases"** and **"only time pass purchases"**. Default: individual and time pass purchases.
![screenshot 2015-02-03 16 06 31](https://cloud.githubusercontent.com/assets/6638286/6022659/a9beecdc-abbe-11e4-9f03-ee5daef94400.png)
- [x] 2) **Hide** the **"Global Default Price"**, **"Category Default Price"** and **"Individual Price"** sections, if this toggle is set to **"only time pass purchases"**.
- [ ] 3) **Show an error flash message**, if the user tries to set this toggle to **"only time pass purchases"**, if **no time pass** exists: "You have to create a time pass, before you can disable individual purchases".

For the case that this toggle is set to **"only time pass purchases"**, the following adjustments are necessary: 

**Add / Edit Post Page**
- [x] 4) **Hide** the **"LaterPay Pricing for this Post"** metabox.

**Post Preview**
- [x] 5) **Hide** the actual statistics within the **post statistics pane** but **still show** the option to switch between "Visitor" and "Admin" view. Show a different heading saying "Post Preview Mode".

**Single Post Page**
- [x] 6) **Hide** the LaterPay **purchase button**.
- [x] 7) **Hide** the LaterPay **purchase link** below the teaser, if the preview mode **"Teaser content only"** is selected in the "Appearance Tab".
- [ ] 8) **Hide** the **box on the LaterPay overlay** (.lp_overlayText), if the preview mode **"Teaser content + full content, covered by overlay"** is selected in the "Appearance Tab".

**Shortcode**
- [x] 9 )For the [laterpay_premium_downloads] shortcode the purchase button should be replaced by a simple hyperlink to the linked content that says "View".

**Comment by twoldrich** [comment]
I just tested with the current master, the biggest part of the changes works fine. 

Some further adjustements are still necessary:

**Pricing Tab**
- The **toggle** can be switched to **"only time pass purchases"** if **no time pass exists**. In that case, the toggle should either be **disabled** or **automatically switched back** to **"allow individual and time pass purchases"**. Also, the respective **error flash message** is currently not displayed.
- In **"only time pass purchases"** mode, the **explanation for PPU and SIS** is not needed and can be hidden as well.

**Single Post Page**
- If the preview mode **"Teaser content only"** is selected, we should have the text **"Buy a time pass to read the full content."** instead of the purchase link. Currently, it is rather unclear for the user how he should proceed to access the content.
- If the preview mode **"Teaser content + full content, covered by overlay"** is selected, the **overlay box** should **not be displayed** (so there should only be a semi-transparent overlay). Additionally, we should display the text **"Buy a time pass to read the full content."** under the teaser content.
- The "view" link in shortcodes should be rendered as a button (see right shortcode below). Currently, this link has no styling (left shortcode below).
![screenshot 2015-02-12 14 16 46](https://cloud.githubusercontent.com/assets/6638286/6168107/710857e2-b2c2-11e4-8db4-9655ee1130b7.png)

**Comment by drdla** [comment]
@twoldrich are we good now?

**Comment by twoldrich** [comment]
@yastapenko-ScnSoft All your fixed work fine, thank you!

There's one more thing, which I just stumbled over: In "Time passes only" mode, it would be good, if we could **hide** the columns for **"price"** and **"price type"** in the post overview. Can you please take care of that?

![screenshot 2015-02-16 20 04 49](https://cloud.githubusercontent.com/assets/6638286/6217717/3d953df0-b617-11e4-9013-729701763fc6.png)

**Comment by drdla** [comment]
Fixed that in my last commit. Closing this ticket now, as I have verified that the custom columns are properly hidden.
