### ISSUE TITLE
Introduce visible and invisible test mode

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#592]
Our test mode is currently designed in a way that allows merchants without a proper staging installation to integrate and test LaterPay without that being visible to their users.

There is also a second option which is hardly described that allows making the plugin behave like it was in live mode while it really is working against the LaterPay sandbox environment (as can be seen on laterpaydemo.com). The trick here is to enter sandbox API credentials in the live API credentials inputs, leave the plugin in test mode, but swap the sandbox and live API URLs on the advanced settings page.

It would be much better to
- remove the possibility to edit the API URLs from the advanced settings page and
- add an option to the Appearance tab that lets the admin choose between "invisible test mode" and "visible test mode"

"Invisible test mode" behaves like our current test mode: LaterPay is not visible at all to visitors and purchase links only trigger an alert instead of rendering the purchase dialog.

"Visible test mode" behaves like an installation in live mode. It should communicate with the sandbox environment though. And because our sandbox environment does not know about any merchants registered in the live environment, it must use the sandbox API credentials when talking to the sandbox environment endpoints.

**Comment by twoldrich** [comment]
Additional info (this might already be the case, I just want to be sure): In case that the admin chooses the "visible test mode", we have to make sure that even **if the logged-in admin has purchased an article**, he can still **switch between the Admin and the Visitor preview**.

**Comment by yastapenko-ScnSoft** [comment]
@AliaksandrVahura-ScienceSoft  Please review, probably i missed something

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Reviewed, see my comments on js, except of that other looks fine.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Please add translations after PR will be merged.

**Comment by yastapenko-ScnSoft** [comment]
@drdla when try to get dialog from sandbox with default credentials get error 500. So i can't guarantee that all will be work for visitors (not admin). And question is^  Is it all ok with sandbox environment?

**Comment by twoldrich** [comment]
- [ ] There is a minor **visual** issue, as "invisible" and "visible" don't fit into the toggle.
![screenshot 2015-02-23 12 02 35](https://cloud.githubusercontent.com/assets/6638286/6326654/393ab716-bb54-11e4-87d9-16863e1cf368.png)


Otherwise, **functionality works fine:**

Tested | Invisible Test Mode | Visible Test Mode | Status
------ | ------------------- | ----------------- | ------
View a post as logged-out visitor | Fulltext is displayed | LaterPay button/link is displayed (Due to #224, teaser is not generated automatically if it doesn't yet exist) | OK
Click purchase button as logged-out visitor | Not possible | Sandbox purchase dialog is displayed | OK
Click purchase button as logged-in admin | Alert is displayed | Sandbox purchase dialog is displayed | OK
Switching between "Admin" and "Visitor" preview | Possible | Possible, also if post has been purchased in test mode.

**Comment by drdla** [comment]
@yastapenko-ScnSoft found more weirdness that needs to be resolved; see FIXMEs and TODOs in laterpay-backend-account.js

**Comment by twoldrich** [comment]
I just tested with the current master:
- [ ] The **flash message** "The plugin is now in invisible/visible test mode" is not displayed when clicking the toggle.
- [ ] Switching to live mode is not saved if the plugin was in "visible test mode" before. Steps to reproduce:
- Switch to **test** mode
- Switch to **visible** test mode
- Switch to **live** mode
- Reload the page
-> **Test** mode is selected.

**Comment by drdla** [comment]
@twoldrich The translations need an update now.

**Comment by twoldrich** [comment]
I updated the translations (and forgot to mention the ticket in the commit...)
