### ISSUE TITLE
Allow merchant to define fallback behaviour in case LaterPay is not responding

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#717]
Downtime of the LaterPay API should not negatively affect the merchant.

The plugin should set a timeout for API requests and react, if that timeout is exceeded.

HOW it reacts should be chosen by the merchant in an advanced setting:
a) Do nothing -> make sure premium content is not accessible for free
b) Give full access to premium content in order to not dissapoint the users
c) Hide premium content, so it is not visible. Direct access would be blocked

**Comment by mturalenka** [comment]
@doismellburning how can we check if the LP API is available to prevent redirections( gettoken etc)
special API call or call to any existent , if we get `200 Ok` in response, taking in account some request timeout(e.g 10s), - everything is ok, other then `200 Ok` - api is not available

**Comment by mturalenka** [comment]
@drdla @doismellburning  any update about the question?

**Comment by doismellburning** [comment]
@mturalenka Good question; I guess probably kick off an async request to `/` while doing the `/identify` iframe load, and ensuring you get a response before doing the redirect? What's your logic for falling back to `/gettoken` anyway?

**Comment by mturalenka** [comment]
@doismellburning the idea was to prevent user from redirection on unavailable LP API, because we loose control on flow - user will stuck at first step `gettoken`.
Current behavior is:
* user opens website
* on server side, when we detect that user doesnt have lptoken, we redirect user on `gettoken` URL;
* user(browser) goes to LP API, 
* LP API redirects user back to our website with lptoken param
* we store lptoken.
* User can see the page
right now without check of the LP API health, we redirect users without token to `gettoken` API, and if the API is down, users stuck on the first step - waiting response from API, as result they cannot use website, until we disable plugin.
so before doing redirect we should check LP API health,  if everything is ok - and only then redirect to API.
if API is not available we should use one of the flow, described by @drdla in this ticket.

as for `identify` request, its used on client side(browser) within iframe, so it doesnt block page loading, so the user does not reach

**Comment by doismellburning** [comment]
> Current behavior is:
> * user opens website
> * on server side, when we detect that user doesnt have lptoken, we redirect user on gettoken URL;

Ah, so you're not using `/identify` at all there? Fun

**Comment by doismellburning** [comment]
Then yep, a pre-redirect check is probably the best way

**Comment by mturalenka** [comment]
@doismellburning `/identify` request is been using on client side, within iframe. and in fact `/identify` request is sent by user(browser) to setup some cookies for LP API domain, so it means its not related to the issue.
what API can we use to check health, i heard you have `http://api.laterpay.net/health` can this one be used? And to reduce load on server side, we can just send `OPTIONS` request instead of 'GET/POST' what can you suggest?

**Comment by doismellburning** [comment]
> `/identify` request is been using on client side, within iframe

Yes, but presumably it happens in advance of the `/gettoken` redirect, and the decision to redirect is based on the response to `/identify` - in which case that's a perfect time to also check API status

> what API can we use to check health

I'd prefer if you checked for not-a-server-error on `/` please.

I realise that probably `4xx`-s right now, but that's a client "error" - `/health` is an internal API that has leaked.

> And to reduce load on server side, we can just send OPTIONS request instead of 'GET/POST' 

`HEAD` please, that's defined as having no response content

Cheers

**Comment by mturalenka** [comment]
@doismellburning do you mean `identify` request with `callback_url` ? so this should allow to get `lptoken`, using only iframes, right?
as for request  to `/`, yes right now it returns `HTTP/1.1 404 Not Found` for HEAD request, at least for this we can say that web server is up, nothing about the application state, but should be ok for now

**Comment by doismellburning** [comment]
> do you mean identify request with callback_url ? so this should allow to get lptoken, using only iframes, right?

That's the idea, yes

> as for request to /, yes right now it returns HTTP/1.1 404 Not Found for HEAD request, at least for this we can say that web server is up, nothing about the application state, but should be ok for now

Nod, I realise that's not ideal, apologies, will aim to have `/` 200. Mind you, if we're well enough to return 404s, we're probably fairly healthy!

**Comment by mturalenka** [comment]
@doismellburning its very hard to handle 404 response within client, we have several transports, that can handle requests: wp, curl, file_get_contents. and all of them reflect on 404 response negatively, like doesnt return content, throws errors/exceptions so its hard to say that service is ok when you get errors. dont you have api that returns `200 ok` on `HEAD` request? `https://api.laterpay.net/health` `https://api.sandbox.laterpaytest.net/health` work well with it, i didnt catch why cannot we use this?

**Comment by doismellburning** [comment]
> I didnt catch why cannot we use this if this is live available?

Because it's something we never considered as a public API.

But I guess we can start...
