### ISSUE TITLE
Statistics: Adjust Calculation of Conversion Rate

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#731]
I was just wondering, how we calculate the **conversion rate** for our posts, especially together with time passes.

From my perspective, we currently simply use:
> **purchases of a post / views of this post**.

So for example:
If 1.000 users view a post a total **1.000 times** and purchased it regularly (via the purchase button) **100 times**, we have a **conversion rate of 10%** – this works fine if you don't have **time passes** on your blog. **With time passes**, it's a bit more complicated, I think. 

Let's say, we still have 1.000 views for a post:

Views | User Description
----- | ----------------
200 | These users have a time pass that covers that post
100 | These users have already bought this post
700 | These users haven't yet bought this post

And let's say, purchases of/from this post are

Purchases | Description
--------- | -----------
80 times | the post is purchased directly (via the LaterPay button)
20 times | a time pass is purchased from this post

Then, the conversion rate should be calculated with:
> **(80 direct purchases + 20 time pass purchases) / (700 users, who haven't bought his post before)**

which would be **14%**.

If we would also take into account the users, who **already bought** the post and the users, who have a **time pass**, we add people who simply *cannot* buy the post.
At the same time, if we neglect the **time pass sales** that are done from a certain post, we neglect, that this post **has converted** (not into a single purchase, but into a time pass purchase). 
Both (**more views** and at the same time **fewer conversions**) lead to **constantly lower conversion rates** than actually true.

@drdla What do you think?

**Comment by drdla** [comment]
:+1:

**Comment by twoldrich** [comment]
Cool, then let's
- [ ] adjust the calculation of the conversion rate ( @AliaksandrVahura-ScienceSoft )
- [ ] change the tooltips / descriptions and contextual help ( @twoldrich )

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Currently we don't track on which post time pass was buyed. Should we track this info? Or you probably you mean "buyed time pass that covered this post from any place"?

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Yes, we would have to track, from which post a time pass was purchased.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Missed commit https://github.com/laterpay/laterpay-wordpress-plugin/commit/82fa8ed59e679f92432d7542d276bbf884cf17a3 in history, cause of incorrect naming.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Currently our view statistics works incorrectly cause we store first view timestamp for user instead of actual. So for example if you viewed page first time on 01.04, and once more on 02.04 - we will store 2 views on 01.04 and no info about 02.04. Ways to solve this:
1. Set user id cookie expiry to the begginning of the next day. In this case new user id cookie will be created each day (if user visited page). This variant will work only if our minimal period for statistics is 1 day. Also timestamp not actual in this case, we can store only date.
2. Store each view as separate row with it's time. Views table will be really huge and we should implement truncate functional first.

**Comment by drdla** [comment]
Option 2) is clearly superior in terms of possible analyses from the stored data.

With proper field types (e.g. enum instead of varchar(256)) the database should be able to handle at least some 10 million rows in a table, which should be ok in combination with the truncation feature for even large sites.
Sheer number of rows is not a problem per se.

Different points of view anybody?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Ok. I also prefer option 2.

**Comment by mturalenka** [comment]
agree with you @drdla, 2) is more suitable

**Comment by drdla** [comment]
Having #16 in combination with this issue would be great.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Need to clarify truncate process, should we store old information or not and where. Also actually this will be not truncate but deletion of old data (older 1 month for example), need to clarify period.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Basically done. Please test. I don't like sparkline on the most/least conversion. Can you please describe what it should display and check it?
