### ISSUE TITLE
Ajax issue: Thumbnails not loaded outside of blog posts

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#811]
A merchant reported, that outside of posts, thumbnail/preview images are not loaded correctly: Instead, only the alt-description is displayed. The URLs of the respective image all look like

http://www.xxxxxxxxx/admin-ajax.php?action=laterpay_load_files&aid=xxxx&ext=.jpg&file=xxxxxxxxxxx-xxxxxxxx%3D%3D&file_disposition=attachment&ts=xxxxxx&hmac=xxxxxx

(xxx replaces customer specific information)

**Comment by mturalenka** [comment]
@twoldrich could you please add more details here.
- explain please what does it mean 'outside of posts', 'thumbnail/preview images'?
generally we have next states:
- plugin is not working: nothing should be changed. images have original url
- plugin is working, post is not  purchased: user see - purchase button, teaser, overlay with short excerpt/purchase link. here under the overlay we get part of the content, if it contains images, they will be secured(url is encoded), and as result under overlay will be empty image  with alt-title - because user doesnt have access to it yet.
- plugin is working, post was purchased: user see full content, images are secured(url is encoded)

**Comment by twoldrich** [comment]
@mturalenka Sorry for being unprecise!
- "Outside of posts" means: Not on a single post page. The customer said, that preview pictures are displayed correctly on the homepage, but not on the individual post pages.
- "Preview pictures": I will post an example in the development channel to illustrate, what I mean.

**Comment by twoldrich** [comment]
Just tested on a test blog: This also affects the image preview in the Media Library: All images have the ...ajax... link instead of the real image.

<img width="430" alt="screenshot 2015-07-15 11 48 38" src="https://cloud.githubusercontent.com/assets/6638286/8695779/8d1c837a-2ae7-11e5-9547-4ab5c17efa1d.png">

**Comment by mturalenka** [comment]
@twoldrich whats remain here?

**Comment by twoldrich** [comment]
@mturalenka I guess, we can close this, as we didn't receive further complaints about missing images.
If we do, I would comment accordingly - thank you!
