### ISSUE TITLE
WPEngine Caching

### ISSUE THREAD

**Issue by ericflarsen** [laterpay/laterpay-wordpress-plugin#919]
WPEngine caching is preventing users from seeing content after purchasing it.

Please implement WPEngine cache control https://wpengine.com/support/cache-control-headers-wp-engine/ just like the varnish caching implemented for VIP Go.

**Comment by PatelUtkarsh** [comment]
Since WPEngine doesn't have any programmatic way to bypass cache we can show admin notice when the plugin is installed on WPEngine and ask the user to contact WPEngine to bypass the required cookies in order for the plugin to work properly with page-cache.

We can also display button called `Done` which will store a value in db which will not show the notice again.

Cookies to bypass for cache:
1. token
2. laterpay_purchased_gift_card
3. laterpay_tracking_code
