### ISSUE TITLE
Voucher price should not exceed time pass price .

### ISSUE THREAD

**Issue by sudhir-yadav** [laterpay/laterpay-wordpress-plugin#959]
![image](https://user-images.githubusercontent.com/3166668/45165887-5e3d5280-b213-11e8-9947-dc0c6d48ee30.png)

**Comment by ksmoore125** [comment]
Could you please add a warning message when this occurs? I wouldn't want someone to keep typing in a higher amount and wondering why on earth it kept getting changed and then getting frustrated ;)

Time Pass Message text: The voucher price must be less than or equal to the time pass price.
Subscription Message text: The voucher price must be less than or equal to the subscription price.

**Comment by ksmoore125** [comment]
Additional Issue Steps to Reproduce:
1) Create or edit a Time Pass or Subscription
2) Generate voucher code and set the price to something less than the default price
3) Click save

Result: 
The voucher price is reset to the default price

Desired Results:
The voucher price should save the price that you typed in

**Comment by thrijith** [comment]
Message text: The voucher **price must be less than or equal** to .....

@ksmoore125 We may need to update this message because if a user tries to set something less than `0.05` for time pass or less than `1.99` fo subscription then that won't work either because that is the lowest price that can be set for time pass and subscription respectively.

**Comment by ksmoore125** [comment]
### Issue (voucher price getting reset to time pass or subscription price)
**This does not appear to be resolved:**
> Additional Issue Steps to Reproduce:
>
>1. Create or edit a Time Pass or Subscription
>2. Generate voucher code and set the price to something less than the default price
>3. Click save
>Result:
>The voucher price is reset to the default price
>
>Desired Results:
>The voucher price should save the price that you typed in

### Enhancement (add warning message)
**See below for additional details:**

- Default View:
![image](https://user-images.githubusercontent.com/41650164/45646506-2a6ef200-ba89-11e8-9498-438e943dd6de.png)

- If user inputs a voucher price less than or equal to the Time Pass / Subscription price then no change:
![image](https://user-images.githubusercontent.com/41650164/45646506-2a6ef200-ba89-11e8-9498-438e943dd6de.png)

- If user inputs a voucher price GREATER THAN the Time Pass / Subscription price then we will:
  1) Show warning message   
  2) Reset price to the Time Pass / Subscription price (like it does now) OR if it is easier, don’t reset the price but disable the Save button
![image](https://user-images.githubusercontent.com/41650164/45646938-48892200-ba8a-11e8-9a55-67aef8eb04e0.png)

NOTE: I am open to other style options for the error message but I did not see any other errors inside our plugin so I copied what is done within LaterPay; the color is #ff1744
![image](https://user-images.githubusercontent.com/41650164/45646692-b41ebf80-ba89-11e8-9712-e02257856ca4.png)

**Comment by thrijith** [comment]
@ksmoore125 This is the updated position/style/behaviour of warning text and save button. ( with mentioned colour

![voucher_warning](https://user-images.githubusercontent.com/13589980/45682867-45ac3100-bb5f-11e8-9c27-87448bb84ad9.png)

Please let me know if this needs change.

**Comment by ksmoore125** [comment]
Sorry to keep sending this back but the validation does not appear to be totally functional.

Steps to Reproduce:
1. Set the voucher price to an amount higher than the time pass price
2. Without clicking anywhere else on the screen, click the Save button
Observed result: It allowed me to save and I never saw the warning message. It did reset the price to the time pass price so this isn't a HUGE deal but if it is easily resolve, it would be nice if it validated sooner.

Additional Symptom of the same issue:
1. Set the voucher price to an amount higher than the time pass price
2. Click somewhere on the screen so that the error message is displayed (it seems like it only shows up if you click Create voucher code)
3. Correct the price
4. Hit tab (note the error message does not go away)
5. Click other places on the screen (note the error message does not go away)
Observed result: The error message does not go away until you click "Generate voucher code" and when this is done it appears to add two voucher codes, one for your new price and one for the time pass / subscription price.

**Comment by thrijith** [comment]
@ksmoore125 Was the subscription price `1.99`?

If that is the case then it won't allow creating a voucher for a price less than that.
A subscription cannot go below the minimum value of `1.99` same goes for the value of the subscription voucher, in the previous versions if someone accidentally entered a price below that, it would have saved that but that subscription wouldn't work ( would redirect to a 404  )

**Comment by ksmoore125** [comment]
That was exactly the issue; sorry, still learning the product as I go!

Could we add an additional warning message for if the voucher price is less than 1.99? 
It should be:
"Subscriptions, like other Pay Now content, must have pricing above $1.99 or 1.49€"

**Comment by thrijith** [comment]
@ksmoore125 

Please check below GIF for the changes.
![subvoucher](https://user-images.githubusercontent.com/13589980/45995234-d7aebf00-c0b4-11e8-8969-282e60ca4782.gif)

Note: It will show an error if client tries to enter price below `1.99`, and it will reset back to `1.99` automatically, it is same behaviour as for time pass when we enter price between `0.01-0.04`

Let me know if this needs change.

**Comment by ksmoore125** [comment]
What you have shown above looks great. Please let me know once it is available for testing on staging.

**Comment by thrijith** [comment]
@ksmoore125  This has been deployed on staging, please test and let me know if it's working for you.
